### ISSUE TITLE
the map does not appear

### ISSUE THREAD

**Issue by CARocha** [caioariede/django-location-field#106]
Hi, since 3 days ago the map does not appear, and it does not throw me any errors in the google chrome console, any idea or where find error?

Django version 2.1.1, using settings 'mywebsite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[19/Nov/2018 21:39:41] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[19/Nov/2018 21:39:41] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[19/Nov/2018 21:39:41] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Not Found: /robots.txt
[2018-11-19 21:39:42,142] log: WARNING - Not Found: /robots.txt
[19/Nov/2018 21:39:42] "GET /robots.txt HTTP/1.1" 404 4172
[19/Nov/2018 21:39:42] "GET /admin/ HTTP/1.1" 200 16892
[19/Nov/2018 21:39:46] "GET /admin/dlf_app/place/add/ HTTP/1.1" 200 10300
[19/Nov/2018 21:39:46] "GET /static/admin/js/inlines.js HTTP/1.1" 200 13813
[19/Nov/2018 21:39:46] "GET /static/location_field/js/form.js HTTP/1.1" 200 19650
[19/Nov/2018 21:39:46] "GET /admin/jsi18n/ HTTP/1.1" 200 7047
[19/Nov/2018 21:40:16] "GET /static/admin/img/inline-delete.svg HTTP/1.1" 200 560

<img width="1408" alt="captura de pantalla 2018-11-19 a la s 21 45 11" src="https://user-images.githubusercontent.com/168115/48750386-759db080-ec44-11e8-8a5b-d1f56489fe38.png">

**Comment by caioariede** [comment]
Did you check the Network tab?

**Comment by CARocha** [comment]
@caioariede yes but don't see any error, the map is missing :/
![captura de pantalla de 2018-11-21 10-56-04](https://user-images.githubusercontent.com/168115/48856545-4a1de180-ed7c-11e8-8952-438d4871b7c4.png)

**Comment by 0rski** [comment]
Same issue here

**Comment by caioariede** [comment]
Sorry guys, I don't have time to investigate this issue right now.

Did you test with prior versions to see if this is a bug introduced in the last version?

Please open a PR suggesting a fix if you find a bug.

**Comment by CARocha** [comment]
the only thing I've found is that it works in version Django 2.0, but in 2.1.x not show the map, is strange :/

**Comment by fpoulain** [comment]
I had the same issue into wagtailadmin. I thought it was due to some inconsistencies with the events since the livequery function was never fired. So I moved away from livequery and it works for me.
Feel free to look at it : https://github.com/fpoulain/django-location-field/commit/b333d155beeeb9541d0396681872fe5c46b8f572

**Comment by alantrick** [comment]
Using fpoulain's code worked for me. Something in the way 2.1 work must be interferring with livequery.

**Comment by fpoulain** [comment]
Livequery seems unmaintained and I guess it doesn't work with recent jquery bundled in django and wagtail's admin.

**Comment by caioariede** [comment]
Cool! @fpoulain can you open a PR? It would be awesome :)

**Comment by caioariede** [comment]
Hello guys! I have a proposal for a fix here: #114 

Can any of you please check if this fixes the issue for you? I'm looking forward to release a new version on PyPI with the fix so you can benefit from it.

**Comment by fpoulain** [comment]
Thanks, I will try it asap.

> I'm looking forward to release a new version on PyPI with the fix so you can benefit from it.

Do you have set a deadline for merge proposals?

**Comment by caioariede** [comment]
any updates @fpoulain?

**Comment by fpoulain** [comment]
Sorry for the laag. I tried the 2.1.0 release and it performs well, out of the box, into wagtail's admin. Congrats :+1

**Comment by caioariede** [comment]
Awesome, thanks @fpoulain :)

**Comment by SergeiMinaev** [comment]
If anyone is facing this issue in new version of django-location-field: don't forget to run collectstatic :)
