### ISSUE TITLE
Upgrading leaflet

### ISSUE THREAD

**Issue by fpoulain** [caioariede/django-location-field#108]
Leaflet is currently in version 0.7.7.

Trying it, I faced numerous GUI bugs. I tried to upgrade it and it worked (for me) as expected.

How do you think about upgrading Leaflet to the stable version?

**Comment by SerhiyRomanov** [comment]
As for me, it's good idea. 
Can you provide PR?

**Comment by caioariede** [comment]
I'd love to see a PR for this :)

**Comment by caioariede** [comment]
Fixed in v2.7.0
