### ISSUE TITLE
Map is not rendering

### ISSUE THREAD

**Issue by Alexander3** [caioariede/django-location-field#122]
When opening change form in admin map is blank.
![image](https://user-images.githubusercontent.com/4659834/56468955-88a2ef80-6433-11e9-871a-5a13fa12a524.png)
After changing city it's refreshed and renders correctly, after saving model it works correctly, problem exists only when opening model that wasn't edited through admin (it was imported).
Dragging map or changing location field don't help. 

I'm using postgis, and `from location_field.models.spatial import LocationField`
Tested in django 2.2 and 1.10, with django-location-field==2.1.0

**Comment by Alexander3** [comment]
:man_facepalming: lat lng order was invalid
corrected import code:  
`row['location'] = f'POINT({row["longitude"]} {row["latitude"]})'`

**Comment by kwhandy** [comment]
wait, I have the same problem here. but I do not use spatial DB and the map just showing a blue screen. what do you mean with you corrected import code?

**Comment by aitoehigie** [comment]
@Alexander3 Your solution is rather vague and unhelpful

**Comment by aitoehigie** [comment]
> wait, I have the same problem here. but I do not use spatial DB and the map just showing a blue screen. what do you mean with you corrected import code?

Did you solve this issue?

**Comment by georgie123** [comment]
Same problem, but I think it is related to Ajax or something like that, beacause it happens in onetomany relation.
When I refresh the page: no problem

**Comment by Alexander3** [comment]
Sorry guys for not explaining enough. I was using `django-import-export` to load data from excel sheet, but I made stupid mistake. By:
> lat lng order was invalid

I mean:
`row['location'] = f'POINT({row["latitude"]} {row["longitude"]})'`
instead of
`row['location'] = f'POINT({row["longitude"]} {row["latitude"]})'`
in code that imported data and created model instances.
So my location was invalid  18N, 54E instead of 54N, 18E. It looks like error because it's just desert, and there's nothing there.
