### ISSUE TITLE
ModuleNotFoundError: No module named 'location_field'

### ISSUE THREAD

**Issue by saladgg** [caioariede/django-location-field#128]
...
......
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1006, in \_gcd_import
File "<frozen importlib._bootstrap>", line 983, in \_find_and_load
File "<frozen importlib._bootstrap>", line 965, in \_find_and_load_unlocked
ModuleNotFoundError: No module named 'location_field'

I encountered this problem after having successfully installed the package to virtual env, did add the app to installed apps and made the right imports.

**My solution was to install the app globally on my machine**, it's a second time am encountering this problem.
Why do some apps need to be added globally for it to work??

**Comment by PolynomialDivision** [comment]
You can not even use virtual environments. :/

**Comment by PolynomialDivision** [comment]
I solved it running

    pip install django-location-field

**Comment by caioariede** [comment]
Please always refer to the documentation: https://django-location-field.readthedocs.io/en/latest/index.html
