### ISSUE TITLE
Zoom is not working

### ISSUE THREAD

**Issue by m-a-k-o** [caioariede/django-location-field#130]
Hi,

I found this PR for fixing the problem with zoom https://github.com/caioariede/django-location-field/pull/77 but in latest release on pip is not working.

I found the part of PR is missing:
```
        if kwargs.get('zoom'):
            self.options['map.zoom'] = kwargs.get('zoom')
```
in location_field/widgets.py  on line: 20.

Thank you!

**Comment by michaelhjulskov** [comment]
do you have a temp workaround for this? In my case I'd rather not touch the package files. thanks

**Comment by michaelhjulskov** [comment]
FYI 
I added this
https://github.com/caioariede/django-location-field/pull/155

If You know a temp workaround, please let me know, thank you

**Comment by michaelhjulskov** [comment]
FYI 
I testet with the latest release 2.7.0 and it works with the zoom value entered in the model parameters :)
Your suggestion worked :)
