### ISSUE TITLE
Help me, this is my first time working with leaflet.js

### ISSUE THREAD

**Issue by kwhandy** [caioariede/django-location-field#132]
Hi! I just try this package, install then do default config just like the docs(also makemigrations and migrate). I open the admin page and click create a new form, but it shows:
![Screen Shot 2019-07-15 at 2 08 54 PM](https://user-images.githubusercontent.com/35983715/61201096-96ec6900-a70d-11e9-926d-676df91078f7.png)
when I typing that New York, that not directly search the city. that includes location and city model like this:
![Screen Shot 2019-07-15 at 2 27 55 PM](https://user-images.githubusercontent.com/35983715/61200991-4ffe7380-a70d-11e9-8c94-6d719c509bab.png)
and the configuration(models.py and settings.py) just like this:
![Screen Shot 2019-07-15 at 2 28 25 PM](https://user-images.githubusercontent.com/35983715/61201186-f8acd300-a70d-11e9-850a-9b5e0040643e.png)
![Screen Shot 2019-07-15 at 2 29 50 PM](https://user-images.githubusercontent.com/35983715/61201221-0febc080-a70e-11e9-91fb-51171c1cc203.png)
Does anyone know what is going on here that makes this package doesn't work for me?

**Comment by caioariede** [comment]
There is now a tutorial for setting up django-location-field with Django admin: https://django-location-field.readthedocs.io/en/latest/tutorials.html#using-django-location-field-in-the-django-admin
