### ISSUE TITLE
Access-Control-Allow-Origin Openstreetmap problem

### ISSUE THREAD

**Issue by humpfreybogart** [caioariede/django-location-field#179]
Hi

I get this error in my console

> Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/search/?format=json&q=DK,%209310,%20vodskov' from origin 'https://unvaccinated.singles' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I did a little digging and it seems like a simple solution is 

this url 
https://nominatim.openstreetmap.org/search/?format=json&q=DK,%209310,%20vodskov

should be:
https://nominatim.openstreetmap.org/search?format=json&q=DK,%209310,%20vodskov

File not found: API no longer accessible via this URL
Using the URL /search/ and /reverse/ (with slashes) is no longer supported. Please use URLs as given in the documentation.

Examples how to change the URL:

You use: https://nominatim.openstreetmap.org/search/?q=Berlin
Change to: https://nominatim.openstreetmap.org/search?q=Berlin

You use: https://nominatim.openstreetmap.org/search/US/Texas/Huston
Change to: https://nominatim.openstreetmap.org/search?q=Huston, Texas, US

See [github issue #3134](https://github.com/osm-search/Nominatim/issues/3134) for more details.

**Comment by humpfreybogart** [comment]
but it appears here like it was already fixed

https://github.com/caioariede/django-location-field/blob/f181773c6ad5337545c1dddc850628c6a355ab08/location_field/static/location_field/js/form.js#L199

**Comment by caioariede** [comment]
Yeah, are you using the latest version?

**Comment by humpfreybogart** [comment]
yes
I found out that it was caused by an old cached version of the included js file
Dont know how I will fix it so its forced loaded

**Comment by caioariede** [comment]
@michaelhjulskov okay, so I think we can close this?

**Comment by humpfreybogart** [comment]
yes I can close it

But please let me know if you have an idea how to force read the new js fil

**Comment by humpfreybogart** [comment]
crap. I cant get it to work, because the browser keeps loading the old cached js file

**Comment by humpfreybogart** [comment]
HI Can I suggest to rename the included JS file if its altered. That would force browser to reload of the included JS file. My customers complain and f5 dont help.
Normally I add a file version in the filename or the script link - that normally solves this issue

Thank you
