### ISSUE TITLE
Save the zoom level from the map widget

### ISSUE THREAD

**Issue by lunanoko** [caioariede/django-location-field#32]
Thinking from the standpoint of the end-user, I would expect the preview map to represent what my users will see on the website. However, only the _latlong_ is saved in the `LocationField`, not the zoom level. I think it'd be nice to have access to the zoom level the user selected in their preview window as this will make it more like a WYSIWYG experience.

**Comment by caioariede** [comment]
I'd be glad to receive a contribution that adds this.

**Comment by Braintelligence** [comment]
Would this require another CharField within the PlainLocationField or should we do this by adding another comma?

**Comment by caioariede** [comment]
Ideally, this would be another field. Storing the zoom level within the `LocationField` is not possible, because its spatial version inherits from a `PointField`.

The idea would be to allow users to specify a zoom field, which we could populate automatically, even if it's hidden in the form.

**Comment by caioariede** [comment]
Closing this for now. Anyone interested in this feature can just submit a PR.
