### ISSUE TITLE
Cant see form on the admin console.

### ISSUE THREAD

**Issue by palash-oswal** [caioariede/django-location-field#34]
The form on admin panel is gone on using the module. 
![bug1](https://cloud.githubusercontent.com/assets/12428457/8005199/d74065d2-0ba4-11e5-97e3-0d66baff92eb.png)
The model is as follows:
![bug3](https://cloud.githubusercontent.com/assets/12428457/8005215/fdf5b394-0ba4-11e5-9c75-b0e96f8d8e02.png)

PS: I'm on mysql non spatial db

**Comment by caioariede** [comment]
What version of Django you were using?

**Comment by caioariede** [comment]
Closing, please reopen if you continue to face this issue.
