### ISSUE TITLE
Example URLs not working

### ISSUE THREAD

**Issue by lukeaus** [caioariede/django-location-field#35]
On readme.md you have:

See the example postgis and example sqlite.

However neither of these 2 links are accessible (Im getting 404s)
https://github.com/caioariede/django-location-field/blob/master/example_sqlite
https://github.com/caioariede/django-location-field/blob/master/example_postgis

Thanks

**Comment by caioariede** [comment]
Thanks for pointing it out.

Those examples were removed since all required configurations are in the README itself.
