### ISSUE TITLE
Rendering widget in custom form

### ISSUE THREAD

**Issue by AlesDokshanin** [caioariede/django-location-field#37]
I am trying to render **PlainLocationFIeld** in my form the following way:
```
class PhotoForm(forms.Form):
    # ...
    geo_query = forms.CharField()
    location = PlainLocationField(based_fields=[geo_query], zoom=10)
    # ...
```

And this results in following error:
> AttributeError at /admin/base/photo/907/
> 'CharField' object has no attribute 'name'

The only way I managed to solve this problem is by setting 'name' attribute to CharfField so my form looks like this:
```
class PhotoForm(forms.ModelForm):
    # ...
    geo_query = forms.CharField()
    geo_query.name = 'geo_query'
    location = PlainLocationField(based_fields=[geo_query], zoom=10)
    # ...
```
But I'm not happy with this dirty solution. I don't have deep understanding of how Django creates forms for models and I guess I'm missing something really important. Is there better way to make PlainLocationWidget work with custom form?
I am using Django 1.7 and python 2.7.

**Comment by caioariede** [comment]
@AlesDokshanin thanks for bringing this to my eyes.

I pushed a fix for this issue. Could you please try with the latest version from master?

Also, instead of using `based_fields=[geo_query]` please use `based_fields=['geo_query']`

**Comment by AlesDokshanin** [comment]
@caioariede sorry for waiting. Everything works fine now, thanks much.
