### ISSUE TITLE
Allow based_fields to given as field names, instead of field references

### ISSUE THREAD

**Issue by lunanoko** [caioariede/django-location-field#38]
What I mean is `based_fields=[city, zipcode]` vs `based_fields=['city', 'zipcode']`.

If I can enter my based fields this way, and django location field looks them up on the model, that would allow me to make use of fields defined in parent models. With the current implementation I have to define every field I want to base the location on on the current model.

**Comment by caioariede** [comment]
This was already achieved in https://github.com/caioariede/django-location-field/issues/37
