### ISSUE TITLE
Let based_fields do relationship lookups

### ISSUE THREAD

**Issue by lunanoko** [caioariede/django-location-field#39]
This would be blocked by #38, but if that is implemented, could we get the feature to let based_on fields span relationships?

The Django admin can do this, for example, in a ModelAdmin's `search_fields` attribute. E.g. `search_fields = ('related_model__attribute',)`.

**Comment by caioariede** [comment]
This is not relevant to `based_fields`. The `based_fields` is only used in the frontend, and they describe which fields will trigger the map update when changed.
