### ISSUE TITLE
Browser autocomplete creates incorrect point

### ISSUE THREAD

**Issue by lukeaus** [caioariede/django-location-field#42]
Hi Team,
thanks for creating a cool app.

I have found an issue recently where if browser autocomplete is used then the location field point is incorrect.

screenshot - good point created on typing
![typing in - address works](https://cloud.githubusercontent.com/assets/5635204/11460637/42f4d51c-9744-11e5-870a-fd3c776f26cd.jpg)

screenshot - bad point created on autocomplete
(Note: the fields in yellow were the browser autocomplete fields)
![autocomplete - address does not work](https://cloud.githubusercontent.com/assets/5635204/11460641/5286a0dc-9744-11e5-9884-e12b311ceec8.jpg)

I have <form ... autocomplete="off">...</form> but a lot of browsers ignore this anyway.

Thanks for your assistance in advance.

**Comment by caioariede** [comment]
I think disabling autocomplete might work here.

Which version of Django are you using?

**Comment by caioariede** [comment]
You could try something like this:

http://stackoverflow.com/questions/28388611/django-admin-autocomplete-off

**Comment by lukeaus** [comment]
Hi @caioariede 
Thanks for the quick response!
I am using django-location-field for:
1. Admin
2. Client/main site

django-admin-autocomplete-off will solve the issue for 1 but not 2.

Any ideas re: solving point 2?

**Comment by lukeaus** [comment]
thanks
I have had a play around with it and it works OK about 90% of the time with autocomplete disabled. I am having trouble reproducing times when it does not consistently work.

I think perhaps if I type really fast in the street field then the point doesn't correctly get picked up. Not 100% sure on that though.

I am using django-location-field for 2 things:
- django admin
- client facing location entering form

Related to the autocomplete, I tested in all major browsers with autocomplete disabled in django/html. 
Due to the haphazard way that autocomplete='off'/'false' depending on which browser you are using and the version there are 2 different autocomplete's:
A. User can autocomplete the entire form (I have disabled this in all browsers)
B. User can autocomplete a single field from their browser history (issue in chrome and firefox, not an issue in IE/Edge due to some hacking and setting autocomplete="off" (where as chrome requires autocomplete="false")

Bottom line is that I am sure that I cannot cover 100% of users browsers with regards to stopping users selecting a pre existing value.

Even if the autocomplete wasn't a problem, I am still having sporadic issues with the location point not being correctly calculated, both in django admin and on the client facing side of our site.

What I do find is that if I do have a bad/inaccurate point created, I just go back and add a space to the end of either street or suburb field and then delete that space. That will always regenerate a correct point for the given address.

It should be noted that the adding then deleting a space hack works for both the point not being correctly generated due to autocompleting a field (or in fact the entire form) or the point not being generated for an unknown reason.

**Comment by caioariede** [comment]
About the **autocomplete issue**, I'm not sure setting `<input autocomplete=off>` is enough.

Did it work in your tests or you also had to set `autocomplete=off` in the `<form>` tag?

**Comment by lukeaus** [comment]
Yes it appears both autocomplete='off' is required for both the <form> and the <input> elements.

Except that it appears chrome does not appear to respect autocomplete='off' and instead prefers autocomplete='false' for both the form and input.
http://stackoverflow.com/questions/15738259/disabling-chrome-autofill/29582380#29582380

This is concurrent with my testing on OSX which shows that:
autocomplete='false' works for the latest version of chrome, but not Firefox or Internet Explorer/Edge.

Added to that it appears that Chrome used to respect autocomplete = 'false' but not does not, meaning that different versions have different autocompleting behaviour.
http://stackoverflow.com/questions/31612867/autocomplete-off-not-working-in-chrome

Also setting to 'off' is not compatible with Firefox:
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

See an ongoing thread here:
https://code.google.com/p/chromium/issues/detail?id=468153

Autocomplete is a bit messy unfortunately...

**Comment by caioariede** [comment]
I'm going to leave the autocomplete thing as is.

I'm not sure if this is a problem to be solved by this library.

**Comment by lukeaus** [comment]
I think the main issue is the patchy implementation of disabling autocomplete for an entire form and also on a per field basis amongst browsers, and even in different versions of the same browser. Because of that I am finding that at times points are not generating correctly if a user selected an autocomplete value even just for a single field.

One work around could be to recalculate the point on submitting the form, that way if one of the addresses was not picked up correctly or was autocompleted the point will still generate correctly (hopefully).

**Comment by Braintelligence** [comment]
Use geocoder package to recalculate it on save.

**Comment by Braintelligence** [comment]
You can see my solution in #43.

**Comment by caioariede** [comment]
> One work around could be to recalculate the point on submitting the form, that way if one of the addresses was not picked up correctly or was autocompleted the point will still generate correctly (hopefully).

I agree. In general, I think that the JS could be rewritten/refactored. The code feels a bit clunky to me.

**Comment by lukeaus** [comment]
Thanks - I will look into this

**Comment by caioariede** [comment]
Closing this for now as we released a new version. The JS was refactored, please reopen if it persists.
