### ISSUE TITLE
Generate coordinates on save / import

### ISSUE THREAD

**Issue by Braintelligence** [caioariede/django-location-field#43]
Hello there.

So I'm importing locations with django-import-export, which have a city, state and country. I use them as based_fields.

When I import them the location field is empty, though. No coordinates were computed. They only get computed if I manually enter the data again in the admin form.

Is there a way to let the coordinates compute on import? Also, how do I render the Google Maps widget in a view/html, so I can show the location on the map to visitors?

EDIT1: It seems to be enough to touch (as in: change value and change it back) one of the based_fields in the admin form for every other based_field to be considered for the computing of the coordinates. Am I assuming correctly that the computation of the coordinates is based on the javascript portion of this package?

EDIT2: I'm implementing a geocoding-step on save of a model now through the geocoder package. Trying to figure out right now how to use "def clean_???" to update the plain location fields coordinates on save.

**Comment by Braintelligence** [comment]
So if anyone else might encounter this problem you can do it like this in the model class:

```python
    def save(self, *args, **kwargs):
        if self.country and self.state:
            g = geocoder.arcgis(self.city + ", " + self.state.label + ", " + self.country.label)
        elif self.country and not self.state:
            g = geocoder.arcgis(self.city + ", " + self.country.label)
        else:
            g = geocoder.arcgis(self.city)
        if len(g.latlng) != 0:
            self.location = str(g.latlng[0]) + ", " + str(g.latlng[1])

        super(Location, self).save(self, *args, **kwargs)
```

**Comment by caioariede** [comment]
Thanks for sharing your thoughts here!

Just to clarify:

> Am I assuming correctly that the computation of the coordinates is based on the javascript portion of this package?

Yes. Coordinates only comes from client-side.

Although I think its time to add such functionality in the server-side. :)

**Comment by Braintelligence** [comment]
You can use my code or something alike to accomplish this easily.
