### ISSUE TITLE
Django 1.9 Support

### ISSUE THREAD

**Issue by mjnaderi** [caioariede/django-location-field#44]
I am using django-location-field 1.6.1 with Django 1.9. All things work correctly, but there is a problem in admin page. The problem does not appear in Django 1.8.7. Based on my tests, this is a Javascript issue.

I have installed django-location-field based on "Basic usage" part of the documentation:

```
    city = models.ForeignKey(City)
    location = PlainLocationField(based_fields=[city], zoom=14, default='')
```

This is the scenario: I set the location in admin and save it. Then when I click on the object to update some fields, I see that location has changed. It has changed to the center of the city specified by `city` field.

In Django 1.9, a `change` event on `city` field is fired at page load (Actually a `change` event is fired for all fields). And django-location-field's form.js code listens to this event, and populates `location` based on it. But this shouldn't be done at page load, but when user changes the `city` field by hand.

For solving the problem, we put these lines in a `$(document).ready(function(){...});`. I don't know if this a proper solution.

https://github.com/caioariede/django-location-field/blob/master/location_field/static/location_field/js/form.js#L147-L175

Soon reply is appreciated.

Thanks.

**Comment by caioariede** [comment]
Hi @mjnaderi,

Thanks for reporting this issue. I'll try to reproduce this and see how your fix performs.

**Comment by caioariede** [comment]
@mjnaderi I'm not being able to reproduce this issue.

Any further instructions would be appreciated.

**Comment by caioariede** [comment]
Closing this for now as we released a new version. Please reopen if it persists.
