### ISSUE TITLE
Installation way incorrect  in README.md

### ISSUE THREAD

**Issue by nerogit** [caioariede/django-location-field#46]
https://github.com/caioariede/django-location-field#installation

Release version does not contains 

> location_field/apps.py
> location_field/settings.py

that files. 

So if I add `'location_field.apps.DefaultConfig'` in `settings.INSTALLED_APPS`, raise error like that.

`
AttributeError: module 'location_field' has no attribute 'DefaultConfig'
`

**Comment by caioariede** [comment]
> The master branch contains unstable code for the 2.x release, that is not ready for production.
You must refer to the 1.6.1 tag for a stable release.

https://github.com/caioariede/django-location-field/tree/1.6.1
