### ISSUE TITLE
[INSTALLATION ERROR] ImportError: No module named apps

### ISSUE THREAD

**Issue by madEng84** [caioariede/django-location-field#48]
In the README i see:

1. Install through pip (or manually place it on your PYTHONPATH).
`pip install django-location-field`
2.  Add `location_field.apps.DefaultConfig` to INSTALLED_APPS your settings.py file

After this, when i launch `./manage.py migrate` I see:

> ImportError: No module named apps
And it is right as you can see in the attachment
![schermata 2016-03-01 alle 12 27 14](https://cloud.githubusercontent.com/assets/2088831/13425732/15ffc028-dfa9-11e5-9353-99148a8af170.png)

Thank you in advance

**Comment by caioariede** [comment]
You have the 1.6.x release installed but is trying to follow the instructions for the 2.x release.

I just uploaded the 2.x release to PyPI. Check it out.

**Comment by madEng84** [comment]
Ok perfect. Thank you
Are there Incompatible changes with the old version?

Regards

**Comment by caioariede** [comment]
Yes, at least a few:

https://github.com/caioariede/django-location-field/blob/master/docs/source/changelog.rst#from-1x-to-2x

**Comment by madEng84** [comment]
Perfect. Thank you
