### ISSUE TITLE
location field + django suit = triggers suits confirm modified form popup window

### ISSUE THREAD

**Issue by dteskera** [caioariede/django-location-field#52]
if you try to leave admin detail view of a model that has a location field in it, even if you didn't changed anything, suit brings a popup windows with a message "You have unsaved changes." are you sure you want to leave this page?

this happens when location field has lat or lng value that ends with zero(s)
e.g. 45.801820,16.0506820

in widgets.py i have changed lines 25:34 with these to fix this issue.

``` python
                if not isinstance(value, six.string_types):
                    lng = value.x
                    lat = value.y
                    value = '%s,%s' % (
                        float(lat),
                        float(lng),
                    )

```

**Comment by SalahAdDin** [comment]
Happen this bug with django-jet also?

**Comment by caioariede** [comment]
Did you confirm this issue isn't something specific to django suit? Please reopen if needed.
