### ISSUE TITLE
Version 1.6.1 supports Django 1.9?

### ISSUE THREAD

**Issue by lastorset** [caioariede/django-location-field#54]
It seems to work fine for me, so I'd recommend updating setup.py to allow using Django 1.9. However, I can't seem to run tox or tests with version 1.6.1, so I can't confirm this.

**Comment by lastorset** [comment]
In case it's useful, this is what happens when I run tox on 1.6.1 on Linux:

> django.core.exceptions.ImproperlyConfigured: Cannot determine the SpatiaLite version for the ":memory:" database (error was "Unable to load the SpatiaLite library extension "libspatialite.so.7" because: /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined symbol: sqlite3_spatialite_init").  Was the SpatiaLite initialization SQL loaded on this database?

I tried googling and APTing for a while, but eventually gave up. :)

**Comment by caioariede** [comment]
Yes, it works. If you can't get it to work with spatial databases (can be very tricky sometimes) you can use the plain text fields.
