### ISSUE TITLE
I'd like to work on a patch but unsure of current branch status

### ISSUE THREAD

**Issue by andybak** [caioariede/django-location-field#60]
We'd like to solve the issue of the map widget not showing in the admin if the fieldset is collapsed. I'm guessing I'll need to store a reference to the map object somewhere so I can trigger a refresh when it becomes visible. 

However my question is about the status of the 2.x code. We're currently on the PyPi branch. I'm not sure whether to fork 1.6 or fork master. How close to being stable is the newer code? Is it still being worked on?

**Comment by caioariede** [comment]
Sorry for the long delay here... all new code should be done in 2.x version which is now the stable.
