### ISSUE TITLE
No module named app.py

### ISSUE THREAD

**Issue by dscapuano** [caioariede/django-location-field#61]
**Documentation:**  Stable is v. 1.6.1
**Documentation:**  States that django-location-field supports Django 1.7 to 1.9 but forces download of Django 1.8.15 during pip install.
**Documentation:**  states that location_field.apps.DefaultConfig should be included in INSTALLED_APPS   but module apps.py does not exist in the PyPi install version.
This installed version has documentation issues.  Wrong version uploaded to PyPi?

**Comment by caioariede** [comment]
Sorry for the long delay, version 1.x is now deprecated. You can just use 2.x now.

**Comment by dscapuano** [comment]
Thank you for updating this.  Your list is valuable because so many 
packages on Pypi are poorly written.

David Capuano
