### ISSUE TITLE
pyinstaller shows : No module named apps when run then executable file.

### ISSUE THREAD

**Issue by mohammedasiftebla** [caioariede/django-location-field#65]
Hi,
Using : linux red hat, django : 1.10, pyinstaller : 3.2, python : 2.7.5
I created a basic django project and tried to make it executable using PyInstaller 3.2,
the project runs fine when given : python manage.py runserver.
when i used pyinstaller : has one traceback : Attribute error: settings object has no attribute ' template_context_processors', how ever the outfile is created in dist dir, when i run the executable file it shows : ImportError: No module named apps. i tried to copy the apps dir from django to project , still same error, checked the apps dir has __init__ file, did all the hidden-import commands, did try hooks,
 please suggest if there is something wrong. or should i switch to some other freezing app.
thanks in advance

**Comment by harshrpatel** [comment]
Having same issue! Kindly reply asap Thanks in advance.

**Comment by mohammedasiftebla** [comment]
hey.. i got it finally working..
the problem was packages were missing.. i installed all of them in a single virtual env along with pyinstaller.
and it works now.
however, it works with the django project, it did not work with fabric for me.
are you using django , fabric  ?

**Comment by mohammedasiftebla** [comment]
here is how i got working.
went to c9.io website, there i was able to run the django project with pyinstaller without any issues.
so i did $pip freeze>requirements.txt and installed the requirements.txt in my virtualenv... it gave few errors that could not find some packages, so i removed those which did not work and installed all the remaining which posible. 
let me know if you still have issues after that...
