### ISSUE TITLE
Maps doesn't render, all other fields as NaN

### ISSUE THREAD

**Issue by ofersto** [caioariede/django-location-field#66]
Hi,
I'm trying to use django-location-field in a custom view (and not in the admin), and the map is acting super-weird.

When I load the page
![image](https://cloud.githubusercontent.com/assets/12147393/20618597/b7d8423a-b2f8-11e6-99b9-4b487027cc40.png)

After I type something in the address box
![image](https://cloud.githubusercontent.com/assets/12147393/20618957/8b615bd6-b2fa-11e6-81f8-21be96f73bad.png)

And the most weird part: It's working just fine in the admin panel

**Comment by SalahAdDin** [comment]
@ofersto Did you solve this problem?

**Comment by ofersto** [comment]
Yes, the problem was that I changed the HTML structure so the script recognized all the form fields as fields to base the location on them
