### ISSUE TITLE
Missing leaflet static files causing errors with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by mixxorz** [caioariede/django-location-field#70]
When you're using the `ManifestStaticFilesStorage`, `collectstatic` fails because it can't find two files. Namely:

* `location_field/images/layers.png`
* `location_field/images/layers-2x.png`

The solution would be either to remove those lines from `leaflet.css` or include the images with the package.

Here's a relevant issue: https://github.com/evansd/whitenoise/issues/96

**Comment by caioariede** [comment]
I can't work on this right now, I would really appreciate if you could submit a PR with the fix. :)

**Comment by mixxorz** [comment]
Sure thing. 👍

**Comment by marteinn** [comment]
@caioariede any Sorry for stressing, but do you have updates on this issue? Right now it's blocking me from solving some cache-busting related issues on a project. My PR should do the trick. Thanks :)

**Comment by camilonova** [comment]
I'm still on this issue

**Comment by mixxorz** [comment]
I think #74 should fix this issue. It's just a matter of getting it merged and creating a new release.

**Comment by caioariede** [comment]
Just pushed a new version: 2.0.3, could you please check if it fixes the issue? thanks!

**Comment by marteinn** [comment]
@caioariede Just tried and it works, thanks for the update!
