### ISSUE TITLE
Default value for PlainLocationField.

### ISSUE THREAD

**Issue by SalchiPapa** [caioariede/django-location-field#76]
It is not clear to me by following the documentation and examples, how does the default value for the `PlainLocationField` works.

I have the following setup:

```python
    city = models.CharField(max_length = 255, default = 'México D.F.')
    bill_address = location.PlainLocationField(based_fields = ['city'], zoom = 7)
```
![image](https://cloud.githubusercontent.com/assets/4594825/22850141/7d76e902-efca-11e6-88f0-56d7a16c7201.png)

As you can see, by default I get a blue background for the map, but as soon as I type a space after **México D.F.** in this example and only then I get to see the map displaying correctly:

![city](https://cloud.githubusercontent.com/assets/4594825/22850218/8cbcf00e-efcb-11e6-95c5-118531ee9027.jpg)

Currently I'm using `PlainLocationField` for prototyping purposes, meaning I don't have a spatial database setup in my laptop, but I will have it setup in the production server (which means I cannot use `Point` here.).

I have also tried using `default = 'México D.F.'` keyword argument in the `PlainLocationField` constructor call, but to no avail.

I'd be glad to send a PR to update the documentation as soon as I'm able to figure this out. Is it possible to do what I'm trying?

Thanks in advance for your help!

**Comment by bluegrounds** [comment]
It's not the proper way to solve this, but I used manage.py's `Provide a one-off default now` option when making the migration.

**Comment by fvgoto** [comment]
Hi @Ismael-VC ,

I don't know all details of this project, but there is the kwarg `initial='$latValue,$longValue'` to the **FormField** (not the ModelField). As a workaround, you could use that one with the corresponding coordinates (comma-separated as one string)...

Or you may try to trigger a 'changed' event on the city field in JS upon load...
(That would maybe be a PR candidate, I guess, if it's done in one of the existing files under `/location_field/static/location_field/`...
Maybe right after [js/form.js#L301](https://github.com/caioariede/django-location-field/blob/master/location_field/static/location_field/js/form.js#L301) - you'll have to make sure the searchProvider has been loaded at that point).
