### ISSUE TITLE
1.10 patterns depricated

### ISSUE THREAD

**Issue by qasimalbaqali** [caioariede/django-location-field#79]
I get the following error when trying to migrate after using django-location-field in my project for the first time. Using Django==1.10.6 

`  File "....../lib/python3.6/site-packages/location_field/urls.py", line 1, in <module>
    from django.conf.urls import patterns
ImportError: cannot import name 'patterns'
`

**Comment by SalahAdDin** [comment]
:+1:

**Comment by pije76** [comment]
+1 for python3 support
