### ISSUE TITLE
Documentation: make it live

### ISSUE THREAD

**Issue by fvgoto** [caioariede/django-location-field#80]
Hey, your documentation (under `/docs/source/`) is great and very helpful!
But I don't see any link to read it comfortably online... (besides nagivating back and forth from dir-index on github.com).

Put it somewhere online (readthedocs, github.io or the like) and put a link in README (or even better in the project head (above dir-index)).

Or, at least, put a link from README to `/docs/source/index.rst` and update that page to make links work directly on github.com...

Would be great and add value to your package!

**Comment by caioariede** [comment]
Finally done it here: https://django-location-field.readthedocs.io/en/latest/

Thanks for the suggestion!
