### ISSUE TITLE
How to load static files?

### ISSUE THREAD

**Issue by JoseTomasTocino** [caioariede/django-location-field#81]
I'm sure I'm missing the obvious here. My form displays a blank space where the map should go, essentially because the static files do not get loaded (or referenced for that matter) in my template. How should I link them? How should I configure the static files?

**Comment by stefanogorla** [comment]
I've the same problem: while the admin example application works very well, there is no documentation about template rendering

**Comment by jupiterkenji** [comment]
My Django is rusty, but I get it to work by quick hack i.e. loading the form.js, jquery.livequery.js and maps.google.com/maps.api manually in my template:

then I have this issue https://github.com/caioariede/django-location-field/issues/78

**Comment by joaoalvesltp** [comment]
@jupiterkenji Can you explain how you have loaded it manually? I too would like it fixed, but for what i am doing a quick hack is enough

**Comment by v-nys** [comment]
I'm seeing the same issue. The code that shows the widget in my admin interface (not just the example one, but my own models) does not work in forms. @jupiterkenji it would be very helpful if you could state exactly how you did this as a workaround, because my own attempt to do this just triggers more errors.

**Comment by jupiterkenji** [comment]
Sorry for late reply, I should pay more attention to my email. What I meant was loading it on template like so:
`{% extends 'base.html' %}
{% load staticfiles %}
{% load sekizai_tags %}

{% block content %}

	{% addtoblock "js" %}
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
		<script src="/assets/location_field/js/jquery.livequery.js"></script>
		<script src="/assets/location_field/js/form.js"></script>
		<script src="//maps.google.com/maps/api/js?key=......"></script>
  	{% endaddtoblock %}`

Hope that helps.

**Comment by caioariede** [comment]
Fixed in #123 

Documentation now includes a section about this: https://django-location-field.readthedocs.io/en/latest/install.html#rendering-form-with-a-map
