### ISSUE TITLE
still map is  not being rendered in templates

### ISSUE THREAD

**Issue by SriNandan33** [caioariede/django-location-field#83]
I have created a model form and rendered in HTML template but map is not visible but allotted area

**Comment by alabarga** [comment]
Same problem, any hint?

**Comment by alabarga** [comment]
looks like it works fine with jQuery v2.2.3 but not with v3.2.0.

**Comment by skiv23** [comment]
I was able to render it correctly in template by copying all location field settings (site-packages/location_field/settings.py) into django settings. Turns out it was not replacing options with default ones.

**Comment by v-nys** [comment]
That's odd. Copying settings does not make the widget render for me. And, unfortunately, jQuery 2 is not an option.

**Comment by caioariede** [comment]
Closing this, please if this is still happening on newer versions you can reopen
