### ISSUE TITLE
Initial map is always rendered at position (0,0) 

### ISSUE THREAD

**Issue by alabarga** [caioariede/django-location-field#84]
Hi, looks like the initial map rendering is not using initial or zoom arguments, it is always at position (0,0)

**Comment by tchaguitos** [comment]
Hey, @alabarga!

You can define initial position on the constructor, like this:

```
# change "FormName"
class FormName(forms.ModelForm):

def __init__(self, *args, **kwargs):
        # change "FormName"
        super(FormName, self).__init__(*args, **kwargs)
        # change "FieldName", "Lat" and "Long" 
        self.initial['FieldName'] = 'Lat,Long'

class Meta:
        model = ModelName  # change
        fields = '__all__'  # or fields list  
```

**Comment by bernd-wechner** [comment]
That is distinctly counter the documentation which uses a Point object:

https://django-location-field.readthedocs.io/en/latest/formfields.html#for-spatial-databases

and moreover,  I'm using class based views and Generic forms and so:

```py
    for field_name, field in form.fields.items():
        if isinstance(field, LocationField):
                mid_lat =  -42.8825088
                mid_lon = 147.32812330000002
                field.initial = f"{mid_lat}, {mid_lon}"  # does not work
                field.initial = Point(mid_lon, mid_lat) # does work!                
```

Does the job. But I'd also like to be able to set the bounding box of the initial view
