### ISSUE TITLE
How to put GOOGLE_MAPS_API_KEY to settings?

### ISSUE THREAD

**Issue by elcolie** [caioariede/django-location-field#88]
I have put key in the `settings`
`GOOGLE_MAPS_API_KEY = <my_key>`
 
```bash
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
_.Ub @ js?key=:40
(anonymous) @ common.js:50
(anonymous) @ common.js:193
c @ common.js:44
(anonymous) @ AuthenticationService.Authenticate?1shttp%3A%2F%2Flocalhost%3A8000%2Fadmin%2Fhouses%2Fhouse%2F3%2Fchange%2F&callback=_xdc_._vkjnxe&token=81302:1
```

**Comment by marlonleite** [comment]
Try it:

GOOGLE_MAPS_API_KEY = "YOURKEYHERE"

LOCATION_FIELD = {
    'map.provider': 'google',
    'map.zoom': 15,
    'search.provider': 'google',
    'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
    'provider.google.api_key': GOOGLE_MAPS_API_KEY,
    'provider.google.map.type': 'ROADMAP',
}

**Comment by elcolie** [comment]
Thanks for the answer. I used `django-geopostion` already.
