### ISSUE TITLE
Django 1.11 Compatibility

### ISSUE THREAD

**Issue by madEng84** [caioariede/django-location-field#96]
Hi guys,
what about Django 1.11 Compatibility?

Django 1.10 is not supported anymore, as you can see [here](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/)

Thanks

**Comment by caioariede** [comment]
Did you try using it in a project running Django 1.11? I'll have a look on this, but it would be great to know the issues you faced.

**Comment by madEng84** [comment]
I'm trying to use it with django 1.11 and python3.6, i have found no issue by now... 
I will let you know if i will find any issue.

**Comment by caioariede** [comment]
Cool, thanks!

I'll be releasing a new version soon and will double check newest versions are compatible.
