### ISSUE TITLE
Django 1.11

### ISSUE THREAD

**Issue by JoannaSM** [caioariede/django-location-field#97]
When can we expect the version for python 3.6 and Django 1.11?

**Comment by Jamim** [comment]
Hi @JoannaSM!
Current version is actually works fine with Python 3.6 and Django 1.11.
I'm going to create a PR to update tests and the readme.
You can check that the tests pass with no issues using the following link:
https://travis-ci.org/Jamim/django-location-field
I also already used `django-location-field
` for a project with Python 3.6 and Django 1.11 and I did not encounter any issues.

**Comment by caioariede** [comment]
This would be awesome @Jamim :)

**Comment by caioariede** [comment]
README and Travis has been updates to cover Python 3.6, 3.7 and Django 1.11, 2.0, 2.1 and 2.2
