### ISSUE TITLE
Not compatible with Django 2.1

### ISSUE THREAD

**Issue by carlmjohnson** [caioariede/django-location-field#98]
I did a basic install and added a `PlainLocationField` to my model, and now the admin crashes with:

```
TypeError: render() got an unexpected keyword argument 'renderer'
```

It seems [on the Django side](https://github.com/django/django/blob/87dc0844a634360182bcb74d491508111ef8a652/django/forms/boundfield.py#L93) it is calling:

```
widget.render(
            name=self.html_initial_name if only_initial else self.html_name,
            value=self.value(),
            attrs=attrs,
            renderer=self.form.renderer,
        )
```

But the `LocationWidget` doesn't accept renderer as a keyword argument.

**Comment by carlmjohnson** [comment]
https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-1

> 2.1: Support for Widget.render() methods without the renderer argument will be removed.

**Comment by CARocha** [comment]
What is the solution? how to change code for working this app?

**Comment by CARocha** [comment]
What is solution working well this apps? i have the same error in django==2.1.1

**Comment by Abhishek9900** [comment]
Solved it by modifying **location_field/widgets.py** as follows
Change line 22 of widgets.py
def render(self, name, value, attrs=None): to def render(self, name, value, attrs=None, renderer=None):
and it works smoothly in Django==2.1

**Comment by caioariede** [comment]
@Abhishek9900 mind submitting a PR? I'd love to get this merged into master so it works for everyone.

**Comment by carlmjohnson** [comment]
Looks like we submitted dueling patches. Mine has wider compatibility. I don't know if you want that or not.
